# Generated by Django 3.0.5 on 2020-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
