# Generated by Django 3.0.5 on 2020-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0002_parameter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='time',
        ),
        migrations.AddField(
            model_name='parameter',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
    ]
