# Generated by Django 3.0.5 on 2020-06-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0003_auto_20200626_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
