# Generated by Django 3.0.5 on 2020-06-27 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0004_auto_20200626_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 6, 27, 2, 1, 0, 541837), max_length=40, null=True, verbose_name='datetime'),
        ),
    ]
