# Generated by Django 3.0.5 on 2020-06-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0005_auto_20200627_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
    ]
