# Generated by Django 3.0.5 on 2020-06-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datetimeapi', '0006_auto_20200627_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='name',
        ),
    ]
